version: '2'

services:
 publisher:
  build: .
  volumes:
   - $PWD/..:/home/dogfish/app
  networks:
   - zerobridge
  command: sh ./shell/scripts/startup.sh watcher-pub.js target.txt

 subscriber:
  extends:
   service: publisher
  command: sh ./shell/scripts/startup.sh watcher-sub.js

 responder:
  extends:
   service: publisher
  command: sh ./shell/scripts/startup.sh responder.js

 requester:
  extends:
   service: publisher
  command: sh ./shell/scripts/startup.sh requester.js target.txt

 responder-cluster:
  extends:
   service: publisher
  networks:
   zerobridge:
    aliases:
     - responder
  command: sh ./shell/scripts/startup.sh responder-cluster.js

 server:
  extends:
   service: publisher
  ports:
   - "3000:3000"
  command: sh ./shell/scripts/startup.sh development ./services/server.js

 debug:
  extends:
    service: publisher
  ports:
   - "3000:3000"
   - "9229:9229"
  command: sh ./shell/scripts/startup-debug.sh development ./services/server.js

networks:
 zerobridge: